services:
  agentarr:
    image: jpyles0524/agentarr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentarr
    env_file:
      - .env
    ports:
      - 5173:5173